TARGET =  swap selection bubble qsort pointerconcept endian pointer2 functionpointer voidpointer arraypointer arrayassignment arraycompare swapfunction sumarrayfunction

all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerconcept : $@
endian : $@
pointer2 : $@
functionpointer : $@
voidpointer : $@
arraypointer : $@
arrayassignment : $@
arraycompare : $@
swapfunction : $@
sumarrayfunction : $@

clean :
	rm ${TARGET}