TARGET =  swap selection bubble qsort pointerconcept endian pointer2 functionpointer voidpointer arraypointer arrayassignment arraycompare swapfunction sumarrayfunction summatrixfunction hellostr charpointeroperation stractexample filepointer filedescriptor dynamicAllocation

all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerconcept : $@
endian : $@
pointer2 : $@
functionpointer : $@
voidpointer : $@
arraypointer : $@
arrayassignment : $@
arraycompare : $@
swapfunction : $@
sumarrayfunction : $@
summatrixfunction : $@
hellostr : $@
charpointeroperation :$@
stractexample : $@
filepointer : $@
filedescriptor : $@
dynamicAllocation : $@

clean :
	rm ${TARGET}