TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii

all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 :$@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@

clean :
	rm ${TARGET}