TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii star one2tenWhile one2tenDoWhile randomTwoint staticLocal functionSum returnValue power dice sumArray sumMatrix findMax findValueinArray scoreGrade procScore averege2022Temp baseball baseballtrue

all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 :$@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@
star : $@
one2tenWhile : $@
one2tenDoWhile : $@
randomTwoint : $@
staticLocal : $@
functionSum : $@
returnValue : $@
power : $@
dice : $@
sumArray : $@
sumMatrix : $@
findMax : $@
findValueinArray :$@
scoreGrade : $@
procScore : $@
averege2022Temp : $@
baseball :$@
baseballtrue : $@

clean :
	rm ${TARGET}