TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii star one2tenWhile one2tenDoWhile randomTwoint staticLocal functionSum

all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 :$@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@
star : $@
one2tenWhile : $@
one2tenDoWhile : $@
randomTwoint : $@
staticLocal : $@
functionSum : $@

clean :
	rm ${TARGET}