TARGET = infinit limit celsius2fahr fahr2celsius charNumber 
triangle triangle2 arithmetics increment literal genderRatio compare compare2 sizeof
oddeven

all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
triangle2 : $@
arithmetics : $@
increment : $@
literal : $@
genderRatio :$@
compare : $@
compare2 : $@
sizeof : $@
oddeven : $@

clean :
	rm ${TARGET}